"""empty message

Revision ID: ed088269c067
Revises: 19124be4b0da
Create Date: 2017-12-09 14:54:15.395883

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ed088269c067'
down_revision = '19124be4b0da'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('character')
    op.add_column('user', sa.Column('character1', sa.String(length=10000), nullable=True))
    op.add_column('user', sa.Column('character2', sa.String(length=10000), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'character2')
    op.drop_column('user', 'character1')
    op.create_table('character',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('character1', sa.VARCHAR(length=10000), autoincrement=False, nullable=True),
    sa.Column('character2', sa.VARCHAR(length=10000), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='character_pkey')
    )
    # ### end Alembic commands ###
